package com.savvas.regression;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class PersonalFormTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void personalForm() {
    driver.get("https://donnish-accrual.000webhostapp.com/Personal_Form.html");
    driver.manage().window().setSize(new Dimension(1390, 1010));
    driver.findElement(By.id("ts_first_name")).click();
    driver.findElement(By.id("ts_first_name")).sendKeys("Savvas");
    driver.findElement(By.id("ts_last_name")).click();
    driver.findElement(By.id("ts_last_name")).sendKeys("Kazantzidis");
    driver.findElement(By.id("ts_address")).click();
    driver.findElement(By.id("ts_address")).sendKeys("Thessaloniki");
    driver.findElement(By.name("Submit1")).click();
  }
}
